export const content = {
  zh: {
    lang: 'zh-CN', locale: 'zh_CN',
    title: 'Port Guardian · 端口守卫 — 让端口自由，让开发继续',
    description: 'Port Guardian 是免费开源的 macOS 与 Windows 端口管理工具。查看 TCP/UDP 端口、追溯进程来源、按项目整理服务，在确认风险后释放开发端口。',
    skip: '跳到正文', navigation: '主导航', languages: '选择语言',
    navFeatures: '功能', navDownload: '下载',
    heroFirst: '让端口自由。', heroSecond: '让开发继续。',
    heroDescription: '看清端口背后的进程，找回被占用的开发节奏。',
    download: '免费下载', source: '查看源代码', platforms: 'macOS · Windows / 免费开源',
    demoLabel: '网页交互演示', demoAction: '试着释放端口', demoReset: '再试一次', demoNote: '仅演示，不会访问本机进程。',
    demoOccupied: 'PORT IN USE', demoAvailable: 'PORT AVAILABLE',
    previewTitle: '你的项目，一目了然。',
    previewDescription: '按项目组织本地端口，快速定位进程、来源与风险。',
    previewAlt: 'Port Guardian 项目工作区：端口按项目分组，展示进程、来源、风险和行内详情。',
    previewCaption: '界面预览使用演示数据，应用显示本机服务。',
    featureOneTitle: '看清来源', featureOneText: '从端口到进程，再到启动它的 IDE 或终端。知道它是谁，也知道它从哪里来。',
    featureTwoTitle: '按项目整理', featureTwoText: '按真实工作目录分组，搜索 TCP / UDP 端口，让并行开发井井有条。',
    featureThreeTitle: '先确认，再终止', featureThreeText: '终止前复核进程身份与风险。保护系统服务，普通终止与强制终止由你选择。',
    downloadTitle: '下一次，继续写代码。', downloadDescription: '一个专注的小工具，留给你更多心流。',
    downloadMac: '下载 macOS 版', downloadWindows: '下载 Windows 版',
    macDetail: 'Apple Silicon & Intel · DMG', windowsDetail: '64-bit · EXE',
    releases: '在 GitHub 上查看 Releases', versionLabel: '当前版本',
    installTitle: '首次安装提示',
    installIntro: '当前安装包尚未进行 Apple Developer ID 签名 / 公证，Windows 也可能显示 SmartScreen 提示。',
    installMac: 'macOS：将应用拖到「应用程序」。首次打开被拦截后，进入「系统设置 → 隐私与安全性」，核对来源后点击「仍要打开」。',
    installWindows: 'Windows：若出现 SmartScreen 提示，先确认安装包来自本项目的 GitHub Releases，再点击「更多信息 → 仍要运行」。',
    installMore: '查看完整安装说明', license: '免费开源 · MIT', author: 'Made by soBigRice',
  },
  en: {
    lang: 'en', locale: 'en_US',
    title: 'Port Guardian — Free your ports. Keep your flow.',
    description: 'A free, open-source port manager for macOS and Windows. Inspect TCP/UDP ports, trace process origins, organize services by project, and review risk before freeing a development port.',
    skip: 'Skip to content', navigation: 'Main navigation', languages: 'Choose language',
    navFeatures: 'Features', navDownload: 'Download',
    heroFirst: 'Free your ports.', heroSecond: 'Keep your flow.',
    heroDescription: 'See the process behind every port. Get back to the code that matters.',
    download: 'Download free', source: 'View source', platforms: 'macOS · Windows / Free & open source',
    demoLabel: 'Interactive web demo', demoAction: 'Try freeing a port', demoReset: 'Try again', demoNote: 'A demo only. No access to local processes.',
    demoOccupied: 'PORT IN USE', demoAvailable: 'PORT AVAILABLE',
    previewTitle: 'Your projects. In plain sight.',
    previewDescription: 'Local ports, organized by project. Processes, origins, and risks at a glance.',
    previewAlt: 'Port Guardian project workspace showing grouped ports, process origins, risk levels, and inline details.',
    previewCaption: 'Chinese interface preview with sample data. The app shows your local services and supports English.',
    featureOneTitle: 'Trace the source', featureOneText: 'From port to process to the IDE or terminal that started it. Know what it is, and where it came from.',
    featureTwoTitle: 'Organize by project', featureTwoText: 'Group by working directory and search TCP / UDP ports. Keep parallel projects in order.',
    featureThreeTitle: 'Review. Then stop.', featureThreeText: 'Check process identity and risk before stopping it. System services are protected; graceful or forced termination is your choice.',
    downloadTitle: 'Next time, keep coding.', downloadDescription: 'One focused little tool. More room for your flow.',
    downloadMac: 'Download for macOS', downloadWindows: 'Download for Windows',
    macDetail: 'Apple Silicon & Intel · DMG', windowsDetail: '64-bit · EXE',
    releases: 'View releases on GitHub', versionLabel: 'Current version',
    installTitle: 'First-time installation',
    installIntro: 'The current macOS build is not Apple Developer ID signed or notarized. Windows may also display a SmartScreen notice.',
    installMac: 'macOS: Drag the app to Applications. If the first launch is blocked, go to System Settings → Privacy & Security, verify the source, and select Open Anyway.',
    installWindows: 'Windows: If SmartScreen appears, verify that the installer came from this project’s GitHub Releases, then select More info → Run anyway.',
    installMore: 'Read the full installation guide', license: 'Free & open source · MIT', author: 'Made by soBigRice',
  },
};
